
GET http://localhost:3000/api/categorias
###

GET http://localhost:3000/api/categorias/10
###

POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "Thriller"
}
###

PUT http://localhost:3000/api/categorias/16
Content-Type: application/json

{   
    "nombre": "Romance",
    "protegida": true
}
###

DELETE http://localhost:3000/api/categorias/12

